version: '3.9'
networks:
  roachnet:
    driver: bridge
services:
  roach1:
    image: cockroachdb/cockroach:v21.2.7
    container_name: roach1
    hostname: roach1
    networks:
      - roachnet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"
    command: start --insecure --join=roach1,roach2,roach3
  roach2:
    image: cockroachdb/cockroach:v21.2.7
    container_name: roach2
    hostname: roach2
    networks:
      - roachnet
    ports:
      - 26258:26257
    volumes:
      - "${PWD}/cockroach-data/roach2:/cockroach/cockroach-data"
    command: start --insecure --join=roach1,roach2,roach3
  roach3:
    image: cockroachdb/cockroach:v21.2.7
    container_name: roach3
    hostname: roach3
    networks:
      - roachnet
    ports:
      - 26259:26257
    volumes:
      - "${PWD}/cockroach-data/roach3:/cockroach/cockroach-data"
    command: start --insecure --join=roach1,roach2,roach3
